
CREATE TABLE IF NOT EXISTS ext (id SERIAL PRIMARY KEY,ext TEXT UNIQUE);

CREATE TABLE IF NOT EXISTS directory (
id SERIAL PRIMARY KEY,
name TEXT NOT NULL UNIQUE,
done BOOLEAN NOT NULL DEFAULT FALSE,
created TIMESTAMPTZ NOT NULL DEFAULT NOW(),
updated TIMESTAMPTZ NOT NULL DEFAULT NOW());


CREATE TABLE IF NOT EXISTS files 
(id SERIAL PRIMARY KEY,
directory_id INTEGER, FOREIGN KEY(directory_id) REFERENCES directory(id) ON DELETE CASCADE,
directory TEXT NOT NULL,
name TEXT NOT NULL,
ext TEXT,
ext_id INTEGER, FOREIGN KEY(ext_id) REFERENCES ext(id) ON DELETE CASCADE,
is_dir BOOLEAN NOT NULL DEFAULT FALSE,
size BIGINT,
keywords TEXT,
mod_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
UNIQUE (path, name, ext, is_dir));

CREATE TABLE IF NOT EXISTS search
(id SERIAL PRIMARY KEY,
input TEXT,
created TIMESTAMPTZ NOT NULL DEFAULT NOW());


CREATE INDEX IF NOT EXISTS idx_ext ON files(LOWER(ext));
CREATE INDEX IF NOT EXISTS idx_keywords_gin ON files USING GIN (to_tsvector('polish', keywords));